### ISSUE TITLE
New search triggered by .search-tag deletion

### ISSUE THREAD

**Issue by JorgeGT** [europeana/search#1]
_Hi! Not sure if this is the correct repo but since this issue is search-related, here it goes:_ 

When I use the search field, search terms are added as "tags" in the search bar, but when you delete one of them a new search is triggered. Since the search takes a bit of time the use of the website is slowed down, plus, I imagine, it adds to the load of the servers.

Consider this example:

1. I search `Madrid`: I get some results and a `Madrid` tag is added.
2. I now add `Map` I get more results and the tags are `Map`, `Madrid`. Nice!
3. Let's say I want Barcelona maps now. I thus delete the `Madrid` tag. As soon as I click on the delete tag button a search is triggered, just for `Map`. This search is useless for me, because I haven't added yet the `Barcelona` search term and thus a lot of random maps are displayed. Not nice! 

This gets even worse if I also delete the remaining `Map` tag, because then a blank search is triggered, retrieving the entirety of the collections (as of now, 53,203,777 results) which takes a couple of seconds, wasting time and server resources.

I'm not sure if this is by design, but in case it is not, I would suggest that a better UX/UI behavior is to not trigger a search on search tag deletion, and instead wait until the user presses enter or clicks the magnifying glass button to trigger a new search.

**Comment by t-hill** [comment]
Hi, Jorge ... 

This all sounds eminently sensible. This particular repo is more dedicated to search weighting and algorithms than it is to UI/UX concerns - but I will raise the issue with the relevant UI and UX people.  I agree in particular that the behaviour when *all* filters have been cleared is pretty clunky ....

**Comment by ashmarriotteuropeana** [comment]
Hi @JorgeGT ! This would come under the [collections repo](https://github.com/europeana/europeana-portal-collections) which covers the interface and interaction.

I agree that we could improve the experience here, it's time consuming having to wait between each filter/tag change. I'll bring this up with the devs and come back to you on this in the next couple of weeks. Cheers - Ash, PO

**Comment by DavidHaskiya** [comment]
Thx. Also saw the Basecamp discussion. If memory serves the team discussed
thus issue during development of Collections. Panos did look into the
keyword interaction and it was also the intention to ajaxify the SERP
entirely. Was never implemented, my fault. Pls discuss with team so that
wheel need not be entirely reinvented.

David
