### ISSUE TITLE
minor issue: update logo and licensing information

### ISSUE THREAD

**Issue by Hobbesball** [europeana/search#12]
## description of issue
- currently the search repo is sporting an old Europeana logo
- the copyright information under 'licensing' is false and should be updated
- the README in general is a bit outdated and could use a new description

## possible solution
- use an updated logo taken from the design assets here: https://pro.europeana.eu/resources/europeana-brand/brand-guidelines 
- delete the 'copyright 2007-2012' part and only keep the (still correct) info about EUPL licensing. 
- update our current README description to: "Europeana is an internet portal that acts as an interface to millions of books, paintings, films, museum objects and archival records that have been digitised throughout Europe. This repository contains our search tools, search algorithms, search plugins, and everything search related to assist in finding that particular record amidst the millions.'

Feel free to assign this issue to me if you want me to update this info.

**Comment by aisaac** [comment]
@Hobbesball can we close this issue now? Apparently you've worked on it in between?

**Comment by marrerom** [comment]
Changes made. Thanks @Hobbesball
